### ISSUE TITLE
pangenomes corrupted

### ISSUE THREAD

**Issue by GaioTransposon** [SegataLab/panphlan#14]
Hi guys, 

Thank you for your tool. 
I have been playing around with it a lot lately. 

Not sure why but I found many pangenomes directories-files to be corrupted. 

panphlan_download_pangenome.py -i Bifidobacterium_animalis 
would return: 

Downloading file of size: 0.24 MB
0.24 MB 100.64 %   0.24 MB/sec  0 min -0 sec
Downloading file of size: 218.36 MB
unable to download "https://www.dropbox.com/s/ai265czo9navhxt/Bifidobacterium_animalis.tar.bz2?dl=1"Downloading file of size: 0.24 MB

It would download the zipped file. Manually unzipping it (which, if uncorrupted, shouldn't be necessary) returns a normal-looking directory, but with which panphlan_mapping.py would produce empty output files. 

A long list of genomes, among which the infamous E. coli would produce this problem. 

Any idea what the problem is? 

Kind Regards
D. Gaio

**Comment by leonarDubois** [comment]
Hello,

thanks for playing with PanPhlAn and highlighting issues.
I just tried downloading Bifidobacterium_animalis pangenome and all went fine. 
However a similar problem already happened to me once with another species. It seems that sometimes a strange issue prevent one to retrieve the file from DropBox. Basically the file is found at the right URL but some empty folder is downloaded. (You can spot it because the download goes way faster than expected). I tried it multiple times and it eventually worked fine. Maybe try putting the download step in a loop or try/catch statement. 
Eventually, if the problem persists and if you need the pangenome for some urgent analysis, let me know, I'll try another way to send you the data.

**Comment by GaioTransposon** [comment]
Morning Leonardo, 

Yes I realized it was a problem with dropbox. I ended up downloading from the browser. That way it worked fine. I need to ask you something else but will create a new issue :) thank you for this
