### ISSUE TITLE
UniRef90 genes to function

### ISSUE THREAD

**Issue by GaioTransposon** [SegataLab/panphlan#15]
Hi guys, 

Question in short: 
Where can I get a UniRef90-to-function mapping database? 

Question in long: 
I wanted to get something similar to what you presented in your paper or in the tutorial. I am talking about the gene groups and functions. 

By following the tutorial I didn't get the same heatmap. 
panphlan_find_gene_grp.py -i profile_LAm -o ../../Lactobacillus_amylovorus/panphlan_Lactobacillus_amylovorus_annot.tsv -p ../../Lactobacillus_amylovorus/Lactobacillus_amylovorus_pangenome.tsv --out_plot heatmap.png -v -a 

the above would only give me a heatmap with colors indicating clusters (not even a legend). 
(Am I missing command options to do this...? )

I don t mind doing it myself but using the annotation info (in my case "panphlan_Lactobacillus_amylovorus_annot.tsv") would only give me UniRef IDs, which I tried to get the function for from HUMANn2's utility mapping, but ...no matches! Possibly a UniRef90-version issue here. 
Do you have a UniRef90-to-function database, anywhere? 

Kind Regards
Dany

**Comment by GaioTransposon** [comment]
I found what happened. 
Pangenomes downloaded via the browser had GO,KEGG,PFAM, etc info
Pangenomes downloaded via panphlan_download_pangenome.py do not have that info ...
A bit weird but I ll see to download it again . Thank you

**Comment by leonarDubois** [comment]
Hi again,

so, maybe things are a bit confused, I should make it a bit clearer in the wiki.
The `panphlan_find_gene_grp.py` script has actually multiple uses. The `--out_plot` parameter will help you get a heat map visualization of the PanPhlAn profile. Basically, it's just supposed to be an automatic way to do it to have a glimpse of what it looks like. You can use also a personal script in Python/R/whatever to plot the profile the way you want.

Then the analysis parameter (`-a`), rename (`--close_analysis`) in the latest version (see last commit in main branch) aims to find genes whose profile across strains is similar (based on Jaccard distance between them) and also look at the overall proximity along the contig of the genes families in that group. We kind of expect genes close together in the reference genome with similar presence-absence profile to either drive the phylogeny of subspecies or (more likely) to be mobile element that should be firther investigated. These genes group will be reported in a tsv output (`-o`).

**Comment by leonarDubois** [comment]
Then regarding the annotation provided in the pangenome folder, here i copy paste you some answer we wrote a couple of days ago in a mail raising kind of the same issue :+1: 

UniRef90 IDs can change over time, since they represent a cluster whose representative member can be actualized.
PanPhlAn pangenome files are generated through an internal pipeline based on a release of the UniRef database from 2019. The main goal here was to keep ID consistent from one of our tools to the other. However, some cluster IDs might have changed over time.
Accordingly, I guess that some UniRef90 IDs will be identified directly, others might have become a member of the cluster but no representative member anymore.
As Francesco, I recommend to solve this the ID mapping tool from UniProt (https://www.uniprot.org/uploadlists/) where you can submit "raw IDs" (for example A0A174CG45 instead of UniRef90_A0A174CG45) and ask them to be mapped from UniProtKB to UniRef90, that way it will provide you the cluster ID (UniRef90 ID) to which you sequence belong.
(Note that you can upload a full list of your IDs of interest at the same time)
Also, if your aim is to get back to some other kind of annotations (GO, KEGG, Pfam ...) I advise you to have a look at the file named panphlan_[your_species]_annot.tsv (that comes with the pangenome downloaded on DropBox) that maps the UniRef90 ID from the pangenome file to some other databases.
