### ISSUE TITLE
Duplicated sam header error in panphlan_map.py

### ISSUE THREAD

**Issue by AUAShen** [SegataLab/panphlan#17]
Dear Panphlan developers,

I had an error message in panphlan: "[E::sam_hrecs_update_hashes] Duplicate entry “XXX” in sam header". I solved this problem by filtering out the Duplicated entries in panphlan_map.py. Is this the correct way to walk-around this error? I am using panphlan-1.3 on the latest released pangenome database. Therefore, I changed a bit file IO part, to make sure the program located the paths correctly. Then I have the sam header duplication problem as mentioned above. It would be very helpful if you could give further advice on this.

Best wishes,
Shen

**Comment by leonarDubois** [comment]
Hello, 

I am advising you to work with PanPhlAn 3.0 (just get the latest commit of the master branch). This version is designed to work with the pangenome database available on DropBox.

With which species are you working ?

**Comment by AUAShen** [comment]
Hi Leonar,

Thank you for the quick response. I will try out 3.0. 

I am looking at different desulfovibrio species. And I realised that the latest pangenome database do not have species Desulfovibrio desulfuricans, which contain in the older version database. Can panphlan 3.0v run on the old pangenome database? 

Best wishes,
Shen

**Comment by AUAShen** [comment]
Hi Leonar,

I have the same duplication error when running Panphlan 3 (downloaded from github). The error says "[E::sam_hrecs_update_hashes] Duplicate entry "QVFA01000001.1" in sam header"

And I am running the command: cat input.fastq | panphlan_map.py -p /data/TOOLS/pangenome/pangenome_DB_2020/Faecalibacterium_prausnitzii/Faecalibacterium_prausnitzii_pangenome.tsv                 --indexes /data/TOOLS/pangenome/pangenome_DB_2020/Faecalibacterium_prausnitzii/Faecalibacterium_prausnitzii -o test_Faecalibacterium_prausnitzii.csv

It would be very helpful if you could give any hints for this error. (this pangenome is downloaded from the latest updates of panphlan a few weeks ago)

Best wishes,
Shen

**Comment by leonarDubois** [comment]
Hi, 

this duplication is an issue some users encounter that might be due to duplicated sequences in the fasta file with genomes contigs (here `Faecalibacterium_prausnitzii_pangenome_contigs.fna` ).
This could be checked comparing `wc -l Faecalibacterium_prausnitzii_pangenome_contigs.fna` and  `sort Faecalibacterium_prausnitzii_pangenome_contigs.fna | uniq | wc -l` that should give roughly half of the previous number.

If you are in this situation and the mapping crashes, just cut the fna file in half (using for example `head -[half of the lines in the fna file] Faecalibacterium_prausnitzii_pangenome_contigs.fna > new_contigs.fna )` and then regenerate the indexes using bowtie2-build (http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#the-bowtie2-build-indexer).

Sorry, this is a bit tedious, but such errors require a checking and rebuilding of the whole pangenome database, and that will take some time.
Hope the solution above will solve your problem quickly. Let me know if you encounter other problems

Best wishes

**Comment by leonarDubois** [comment]
The last commit provides an updated/cleaned version of the database that should fix this issue
