### ISSUE TITLE
working with mapping files - enquiries

### ISSUE THREAD

**Issue by GaioTransposon** [SegataLab/panphlan#18]
Sorry it's me again. 

I am working with the raw mapping files, output of panphlan_mapping.py. 
Q1: The second column representing coverage, is it normalized by sample (library) size or is it raw? 
Q2: If a read (150 nt long) maps once, will it show 150 or 1 ? 

And additional question: 
Q3: Is there anywhere a description of what each column stands for in the pangenome files? example: (e.g.: Lactobacillus_amylovorus_pangenome.tsv) I am not sure which ones represent strains IDs and which ones are genes or gene families instead.

**Comment by leonarDubois** [comment]
Hello,

Q1 &2 : 
for these technical questions, the best would be to look further in the code if you have time (function `genes_abundances` in `panphlan_map.py`). Basically, after the bowtie2 mapping, the piling up method from Samtools is called. For details look [here](http://www.htslib.org/doc/samtools-mpileup.html). This leads to a file with [pileup format](https://en.wikipedia.org/wiki/Pileup_format) summarizing the aligned reads on each base of the sequence.

Then, for each read that was aligned, PanPhlAn will check for each gene, if the reads got aligned on a position (base) belonging to this gene sequence region, then it increase the coverage value of the gene by 1. So you could see the value in the output file as the number of reads aligned to that gene.

However, keep in mind that during the next step (the profiling `panphlan_profiling.py`), this coverage value is normalized based on genes families size (how many genes in the same UniRef90 cluster) and their average length. You can get it with the `--o_covmat` of `panphlan_profiling.py`

Q3 : 
The fields are : 
1. UniRef90 cluster IDs
2. gene ID 
3. genome ID
4. contig ID 
5. start position
6. stop position
(I'll add this in the wiki, thanks)

Hope everything's clear, don't hesitate if you have other questions

**Comment by GaioTransposon** [comment]
Thank you Leonard, 

So I take it that library size normalisation is not directly applied, right? 
This could add a strong bias to the results. 
More DNA > more chance of any hit.

**Comment by leonarDubois** [comment]
Hi,

indeed, there is no such things as library size normalization that is applied. Thus, some samples are mapped with kind of an advantage. However, gene families are assessed present or not based on the plateau in the coverage curve. Differences in library size will lead eventually in different heights in the plateau. But since this information is summarized to 1 or 0 in the profile matrix, it does really impact the final results.

However, it does impact the gene families at the tail of the curve whose coverage is too low to be included in the plateau. For some, we can think that a bigger library could change the final outcome (1 or 0, present/absent).

If you have further interest in this kind of results, I suggest you to try the `--o_idx` output argument that gives you a profile matrix not only with 1 or 0 for a binary presence or absence but rather values in -1,-2,-3 or 1, meaning :
1 means plateau area of gene-families 
-1 means multicopy core genes (left from plateau), present also in other species
-2 means undefined gene-families between plateau-level and zero 
-3 means "clearly" non-present gene-families
keeping in mid that -1 and -2 gene families might be strongly impacted by library size.

Hope all of this clarifies the process and bias sources. Thanks for your patience.

Best
