### ISSUE TITLE
How to obtain chocophlan pangenome.csv?

### ISSUE THREAD

**Issue by tamburinif** [SegataLab/panphlan#2]
Hi there,

I'd like to try version 1.3 of panphlan, but when I run panphlan_new_pangenome_generation.py as follows:

```panphlan_new_pangenome_generation.py -i databases/bvulgatus/ -c bvulgatus20 -o bvulgatus20 --verbose```

I get the following error:

`Error: Pangenome file (databases/bvulgatus/panphlan_bvulgatus20_pangenome.csv) not found`

I can see from the Pangenome generation wiki page that pangenome generation now requires ChocoPhlAn export as input, but it's unclear to me what exactly this is or how to obtain it. I can't figure it out from the tutorial either. Any pointers would be appreciated! Thank you!

**Comment by leonarDubois** [comment]
Hi there !

In PanPhlAn version 1.3, there are two scripts concerning pangenome generation. 
`panphlan_pangenome_generation.py` is the legacy version (from v1.2), where the user provide fna/ffa and gff file and generate the pangenome by himself.
The new version `panphlan_new_pangenome_generation.py` that is simply generating the bowtie2 indexes needed for the next step (`panphlan_map.py`) using an existing pangenome fna file.

Existing pangenome are available in the link on [this page of the wiki](https://github.com/SegataLab/panphlan/wiki/Pangenome-generation-(old)). The Dropbox folder containing the pangenomes can be found in [here](https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACJGJqmCh8xSqF7iZWUTdwYa). However is has not been updated since 2016 and is likely to be obsolete.

We are currently working on generating a newer and more complete pangenome database that will be available soon (next week, if everything's fine). At the moment I can send you more recent pangenome files that I have for the species of interest.

Tell me if you need anything else and thanks for pointing out these issues that still need to be fixed or better explained in the docs.


[Bvulgatus.tar.gz](https://github.com/SegataLab/panphlan/files/4488629/Bvulgatus.tar.gz)

**Comment by tamburinif** [comment]
Thanks very much for your prompt reply! I appreciate you providing the B. vulgatus pangenome files and I will keep an eye out for the new pangenome databases coming soon. Thanks!
