### ISSUE TITLE
Using RAST annotations

### ISSUE THREAD

**Issue by minna-miha** [SegataLab/panphlan#29]
Hi there,

I ran panphlan using the original script (eg Uniprot database annotations) and the output presence/absence heatmap made sense. However, I wanted to be consistent with my previous analyses that used RAST annotations, so I made my own ran panphlan using my own annotations by creating my own pangenome.tsv file, etc. 

At first glance I thought it worked successfully. However, at closer look I realized that the read samples used to build the references genomes are showing up with gaps (see attached figure), which did not occur when using Uniprot annotations as is embedded in the panphlan tutorial. 
![heatmap_presAbs](https://user-images.githubusercontent.com/47035328/112196871-78748b80-8bd9-11eb-929a-473f774fe531.png)

I am trying to wrap my head around why this might be happening. I am still troubleshooting and trying to see if there was an error on my end somewhere along the way. However, I was wondering whether it might be due to some sort of incompatibility - should PanPhlan be able to work with annotations other than Uniprot? Any other ideas about what may be happening here?

Thank you in advance for your feedback!

**Comment by leonarDubois** [comment]
Hello,

Thanks for your interest for PanPhlAn
first, know that this kind of issue (non-directly related to the code) should better be raised on the [bioBakery help forum](https://forum.biobakery.org/).

The problem here is that the default annotation is indeed based on Uniprot data, but it is the UniRef90 (based on the 01/2019 release). Thus, in also serve as a clustering of the gene families and is needed for the normalization of the read mapping coverage.

Consequently, it is not advised to replace the UniRef90 with something else. Instead, what you can do is to create a mapping of UniRef90 to your custom annotations of interest. It won't change the final presence/absence matrix, but it will give you some new pieces of information.

Hope this answer your question. Feel free to ask if not.
Léonard


PS: unrelated stuff, and it might depends on why you are using PanPhlAn, but a way to improve the matrix visualization could be to "prune" it. Basically I remove all the gene of the pangenome present in more than 90-99% of the sample and/or less than 10-1%. Thus, I focus on the variable part of the pangenome, and I avoid a big monocolour chunks in the final figure. See also [here](https://forum.biobakery.org/t/tutorial-guidance-on-vizualisation/1741)

**Comment by minna-miha** [comment]
Hi there,

Thank you for the quick response! I just want to quickly make sure I was
clear in my initial explanation -- I created my own annotation file with
the cluster information. So I basically skipped the gene exporter step and
made the associated files myself, using my own annotations & cluster
information. The heatmap results using UniPort vs my own annotations are
(nearly) identical, except for the one funky bit that I mentioned in my
initial posting, so it appears to be mostly working - I just wasn't sure
whether the section that is weird has to do with an error on my end or if
the panphlan script necessarily cannot fully/properly support custom
annotations.

So I guess I just wanted to clarify what I had done on my end before
concluding that PanPhaln doesn't support the particular approach I took.

Thank you,
Michelle
