### ISSUE TITLE
PanPhlAn RNA-seq using latest version of panphlan

### ISSUE THREAD

**Issue by fconstancias** [SegataLab/panphlan#8]
The wiki mention that <https://github.com/SegataLab/panphlan/wiki/PanPhlAn-profiling> panphlan  can be used to quantify the "In-vivo transcriptional activity of individual strains of a species" when paired metagenomes and metatranscriptomes are available.
However, this is only mentionned in the tutorial of version 1.3 of panphlan and not in the latest version. 

Is it still possible to perform such quantification using the latest version?

**Comment by leonarDubois** [comment]
Hello,
yes indeed if you have both metagenomics (DNA) and metatranscriptomics (RNA) samples available it is possible to get a transcription rate of individual strains, but only in the 1.3 version. It should be adapted to the newest version very soon.
Since the mapping of both version are identical, you can use version 1.3 to do that. The main difference will be the way you provide the pangenome file.

**Comment by fconstancias** [comment]
Hello,

> It should be adapted to the newest version very soon.

Do you have any estimation of the timeline ? :)

I have created a specific conda environment for v1.3 but I am encontering the following error:
```
python --version
Python 3.7.6
```

```
(panphlan13) /datadrive05/Flo/Saliva/Saliva2/panphlan/panphlan13$ /datadrive05/Flo/tools/panphlan13/panphlan/panphlan_map.py --help
Traceback (most recent call last):
  File "/datadrive05/Flo/tools/panphlan13/panphlan/panphlan_map.py", line 20, in <module>
    from .utils import end_program, show_interruption_message, show_error_message, time_message, find
ImportError: attempted relative import with no known parent package
```

Any idea what I have been doing wrong here?

Thanks

**Comment by leonarDubois** [comment]
Hi, 

> Do you have any estimation of the timeline ? :)
I hope, by the end of the week.

**Comment by fconstancias** [comment]
Hi @leonarDubois,
Do you have any update. Sorry to instist but I have my DNA/RNA mappings ready...

Thanks a lot.

**Comment by leonarDubois** [comment]
Hi,

I am currently focusing on it. We needed to prepare an update of the pangenome databases first. I'll let you know as soon as I push the code

**Comment by leonarDubois** [comment]
Hi, 

I just pushed to the 3.0 branch an attempt of adapting the code of the 1.3 version to the 3.0 regarding the meta-transcriptomics.
I'm still working on it, and will look for further improvement focusing on the filtering and normalization steps that I'm not sure are working properly at the moment. If you want to try it, get the last version and uncomment line 920 in the profiling script.
Things might not be stable yet, since the 3.0 release in not final yet

Let me know if you have any comment/question. Meanwhile, I'll keep focusing on these.

**Comment by fconstancias** [comment]
thanks @leonarDubois !
